[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "radprocess"
description = "A package that runs a postprocessing pipeline of MHD simulations using multi-fluids models."
readme = "README.md"
authors = [{name = "Sacha Gavino", email = "sacha.gavino@unibo.it"}]
dynamic = ["version"]
requires-python = ">=3.10"

dependencies = [
    "numpy=2.2.2",
    "scipy",
    "cython==3.1.6",
    "zarr",
    "numcodecs",
    "matplotlib",
    "gradio",
]