[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "radprocess"
authors = [{name = "Sacha Gavino", email = "sacha.gavino@unibo.it"}]
dynamic = ["version", "description"]