[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "radprocess"
version = "0.1.0"
description = "A package that runs a postprocessing pipeline of MHD simulations using multi-fluids models."
readme = "README.md"
authors = [{name = "Sacha Gavino", email = "sacha.gavino@unibo.it"}]
requires-python = ">=3.11"

dependencies = [
    "numpy==2.2.2",
    "scipy",
    "cython==3.1.6",
    "zarr",
    "matplotlib",
    "gradio",
    "rich",
]

[project.scripts]
radprocess = "radprocess.cli:main"